number = int(input('введите целочисленное значение '))
print(type(number))
number_word = str(input('введите целочисленное значение которое будет конвертировано в str '))
print(type(number_word))
number_float = float(input('введите целочисленное значение которое будет конвертировано в float '))
print(type(number_float))

float_number = float(input('введите числа с запятой '))
print(type(float_number))
float_string = str(input('введите числа с запятой которые будут конвертированы в str '))
print(type(float_string))
float_number = float(input('введите числа с запятой которые будут конвертированы в int '))
float_number = int(float_number)
print(type(float_number))
